### ISSUE TITLE
metadata option unworking

### ISSUE THREAD

**Issue by Nilad** [kblin/ncbi-genome-download#105]
# version of ncbi-genome-download 
`0.2.11`

# command
```
python3 ncbi-genome-download/ncbi-genome-download-runner.py --verbose --genus "Kluyvera" --metadata
-table data.tsv --format fasta -p 10 --retries 1 bacteria
```

# result

All genomes are downloaded but the data.tsv file doesnt contains the metadata, only the header.

```
cat data.tsv 

assembly_accession	bioproject	biosample	wgs_master	excluded_from_refseq	refseq_category	relation_to_type_material	taxid	species_taxid	organism_name	infraspecific_name	isolate	version_status	assembly_level	release_type	genome_rep	seq_rel_date	asm_name	submitter	gbrs_paired_asm	paired_asm_comp	ftp_path	local_filename
```

**Comment by kblin** [comment]
I'm seeing the same thing, The metadata table works when downloading GenBank format files, which is my main use case. It's not working when downloading fasta format files. I'll investigate.

**Comment by kblin** [comment]
Hm, I guess I confused myself a bit because the metadata table isn't written unless files are downloaded. It looks like the issue is in the parallel downloads and probably has to do with #103 and the way process pools work in Python.

**Comment by kblin** [comment]
As a workaround, you can run `ncbi-genome-download` in single-process mode, that will fix writing the metadata table.

**Comment by Nilad** [comment]
Yes, it's works with `-p 1`.

I think it would be a nice thing to do in parallel download because few genus are very huge and i use `Bacsort` tools to perform taxonomic clean up and in this script https://github.com/rrwick/Bacsort/blob/master/scripts/download_genomes.sh the download command is performe in parallel.

I let you choose to close this thread or to keep it up until the resolution of this problem.

**Comment by kblin** [comment]
Yeah, I agree. It's just not trivial to fix after the recent change to also parallelize the download checking, but I would like to fix it.
