### ISSUE TITLE
Connection issue due to ftp address? 

### ISSUE THREAD

**Issue by elzerac** [kblin/ncbi-genome-download#108]
I am experiencing connection issues as described in multiple other issues (e.g. #104 ) and I was reading the [NCBI Genome FAQ](https://www.ncbi.nlm.nih.gov/genome/doc/ftpfaq/#downloadservice) which states : "These two paths are equivalent hence they do currently provide the same content, however, ftp://ftp.ncbi.nlm.nih.gov/ is the preferred path and the abbreviated path, ftp://ftp.ncbi.nih.gov/, may not be supported indefinitely." 

I am wondering whether ftp://ftp.ncbi.nih.gov/ is no longer supported?

**Comment by kblin** [comment]
That address still resolves fine on my machine, and works both from an FTP client and ncbi-genome-download

**Comment by elzerac** [comment]
Thanks for looking into this! I've tried this on a different machine and it seems like the connection issue is generated because of connection to my cluster rather than an issue of ncbi-genome-download. FTP address seems to work fine now, but may be important to change in the future due to NCBI's ominous warning. Closing the issue. Thanks again!
