### ISSUE TITLE
Python version requirement not listed

### ISSUE THREAD

**Issue by tomck** [kblin/ncbi-genome-download#11]
After having an issue with "requests" which was resolved, oddly enough, by following the easy_install suggestion in chrippa/livestreamer#384, it seems that there may be a feature which requires a minimum of Python 2.7.

There is [a solution for Python 2.6.6](http://stackoverflow.com/a/8498327/6338845) for those of us stuck on older distros, but I don't know if it can be implemented.

home path altered to $HOME for following block to reduce line length
```
ncbi-genome-download bacteria
Traceback (most recent call last):
  File "$HOME/.local/bin/ncbi-genome-download", line 9, in <module>
    load_entry_point('ncbi-genome-download==0.1.8', 'console_scripts', 'ncbi-genome-download')()
  File "$HOME/.local/lib/python2.6/site-packages/ncbi_genome_download/__main__.py", line 59, in main
    ncbi_genome_download.download(args)
  File "$HOME/.local/lib/python2.6/site-packages/ncbi_genome_download/core.py", line 50, in download
    args.assembly_level, args.genus, args.parallel)
  File "$HOME/.local/lib/python2.6/site-packages/ncbi_genome_download/core.py", line 67, in _download
    download_jobs.extend(download_entry(entry, section, domain, output, file_format))
  File "$HOME/.local/lib/python2.6/site-packages/ncbi_genome_download/core.py", line 98, in download_entry
    checksums = grab_checksums_file(entry)
  File "$HOME/.local/lib/python2.6/site-packages/ncbi_genome_download/core.py", line 139, in grab_checksums_file
    full_url = '{}/md5checksums.txt'.format(http_url)
ValueError: zero length field name in format
```

**Comment by kblin** [comment]
Hi there, thanks for your bug report. `ncbi-genome-download` should work on all currently maintained versions of Python.

I'm afraid Python 2.6 support isn't very high up my list of priorities. This project was started in 2016-05-03, and Python 2.6 was end-of-lifed by the Python developers 2013-10-28 (https://www.python.org/dev/peps/pep-0361/).

As I'm trying to support both python 2.7 and 3.3+ from the same code base, every older release of Python I'm also trying to support will make the development process harder. Adding indexes to the string formats is trivial, of course, but if I commit to supporting 2.6, I'll have to make sure I'm not breaking something else in future releases.

I will of course happily accept patches to make `ncbi-genome-download` work on Python 2.6, provided they don't break any of the supported versions, and don't add too much visual clutter to the code.

I will also be adding a more explicit note about the supported Python versions to the README file.

**Comment by kblin** [comment]
As mentioned in the README file now, I suggest using [Linuxbrew](http://linuxbrew.sh) to get a more up-to-date version of python if you are stuck on 2.6 or worse.
