### ISSUE TITLE
This app is not responding.... 

### ISSUE THREAD

**Issue by furqan915** [kblin/ncbi-genome-download#131]
Hi,
I have written this command on linux terminal
`ncbi-genome-download bacteria -s genbank -g 'Staphylococcus aureus' -l complete -F fasta -o /home/honey/`

But nothing was downloaded in the output directory. I have further added `--verbose` and `--debug` as you have already mentioned somewhere in the issues. But it never worked except if I only write Staphylococcus (bacteria genus name) in -g flag.

I don't want to download the whole genus that is why I am just attempting to download this desired species.

**Comment by kblin** [comment]
Hi there,
I'm afraid I can't reproduce the issue. running `ncbi-genome-download bacteria -s genbank -g 'Staphylococcus aureus' -l complete -F fasta` does download files for me. There's 728 complete _S. aureus_ assemblies in GenBank at the moment, so this takes a while.
You should start to see output the moment parsing the `assembly_summary.txt` file has finished, though, that only takes a couple of seconds for me.

**Comment by furqan915** [comment]
Thanks for the help. After waiting for a short while, it finally started downloading.
