### ISSUE TITLE
Feature request: Download a number of accession IDs ...

### ISSUE THREAD

**Issue by phiweger** [kblin/ncbi-genome-download#134]
... like "GCA_001511415.1" etc.

Is this something that could be implemented?

Kind regards

**Comment by kblin** [comment]
The tool can do this already. Check out the `--assembly-accessions` parameter in the README and `--help` output.

**Comment by kblin** [comment]
Keep in mind that the GCA prefex means this is a GenBank accession, so you'll also have to use `--section genbank` to download.

**Comment by phiweger** [comment]
awesome tool, thanks a lot!
