### ISSUE TITLE
Complete genomes can be 'complete' or 'chromosome'

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#14]
We have a problem with bacterial genomes that sometimes the `assembly_summary.txt` file says `complete` and sometimes it says `chromosome` for finished bacterial genomes.

This is partially to do with the fact that bacteria usually only have 1 chromosome, but partially because they have plasmids too. It's confusing.

If I want both, can I do `-l complete -l chromosome` to get both?
Or so I run 2 commands with same `-o folder`?

**Comment by kblin** [comment]
It seems that `chromosome` means that there can still be gaps in the assembly, but the gaps need to be of known size. Short reads that likely fill the gaps are frequently also included. I've not seen this in `complete` records.

In any case, you can always run `ncbi-genome-download` multiple times with the same output dir and different options to get exactly the set of downloaded files that you want.

Allowing multiple `--assembly-level` would be nice, as would be allowing multiple `--format` parameters, and some others. But it also makes the CLI more and more complicated, not to mention the code. :)

**Comment by kblin** [comment]
I will add this to the documentation. I'm just beginning to think that the features are outgrowing the README file and I need to start doing this properly.

**Comment by tseemann** [comment]
There is also overlap between `taxid` and `division`
eg. using `-t 2` (or `-T 2` ?) is the same as using `bacteria` at end.

**Comment by tseemann** [comment]
I am thinking if `--assembly-level` or `--format` contain a "comma" `,` character then you could convert into a regexp and match using regexps in your filtering logic.

For example `--format genbank,fasta,wgs` would become `^(genbank|fasta|wgs)$`

And `--format protein-cds` would just be `^(protein-cds)$` etc

I've used this method in my tools before and it works well.

**Comment by kblin** [comment]
That's not quite how the input parsing works, but it shouldn't be too hard to do this.

**Comment by kblin** [comment]
I think @rhpvorderman's patches take care of this use case, don't you think?

**Comment by kblin** [comment]
The new 0.2.6 release contains the patch from @rhpvorderman that allows you to use `--assembly-level complete,chromosome`. That should take care of this use case, right? If not, feel free to reopen this issue.
