### ISSUE TITLE
Enhancements based on official API

### ISSUE THREAD

**Issue by 444thLiao** [kblin/ncbi-genome-download#177]
Hi, fantastic work and I have a few suggestions for that recently.

I noticed that NCBI recently provided an official API for downloading and assessing the metadata of multiple types of data. I think it would be a chance to enhance the tool based on the official API.

In case you didn't notice that here is the link to its documentation [NCBI Datasets Documentation](https://www.ncbi.nlm.nih.gov/datasets/docs/v1/)

**Comment by kblin** [comment]
Hi there, thank you for your patience. I don't think interacting with the datasets API is in the scope for `ncbi-genome-download`. I think the datasets API already comes with a command line tool the NCBI provides, so if you're interested in using that API, have a look at that.
