### ISSUE TITLE
All virus download errors

### ISSUE THREAD

**Issue by xiaozhazha123** [kblin/ncbi-genome-download#178]
When I download all the viruses,I use this instruction:
ncbi-genome-download --format fasta viral -o /data
As a result, there is only md5sums file and no FASTA file. What's going on
ERROR: Download from NCBI failed: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='Index of /', port=443): Max retries exceeded with url: /genomes/all/GCF/000/837/105/GCF_000837105.1_ViralMultiSegProj14079/md5checksums.txt (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f5dfc3e0a90>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)

**Comment by kblin** [comment]
You have a networking issue reaching the NCBI servers, nothing ncbi-genome-download can do about this (apart from providing a better error message). Please try again later to check if it's a transient issue.
