### ISSUE TITLE
perfect match option?

### ISSUE THREAD

**Issue by RichardCorbett** [kblin/ncbi-genome-download#179]
I've been trying to find a way to download the reference genome used in the kraken2 default db.    I was pleased to find your project which seems to help simplify some of the required steps.

In my kraken2 output I get the following summary report:
```
...
  0.08  94921   0       F1      2169595                 Firstpapillomavirinae
  0.08  94921   0       G       333750                    Alphapapillomavirus
  0.08  94921   0       S       337041                      Alphapapillomavirus 9
  0.08  94921   94921   S1      333760                        Human papillomavirus type 16
```

I've been trying to download the reference genome for "Human papillomavirus type 16", but when I use the following command:
`ncbi-genome-download -S 333760 -F fasta,assembly-report   -l complete all` I get the error message, "ERROR: No downloads matched your filter. Please check your options.".    I think this is likely because HPV16 is listed at a level below species.

However, I can get a positive result if I use the genera search with:
`ncbi-genome-download -g "Human papillomavirus type 16" -F fasta,assembly-report   -l complete all`.   This time I get result for "Human papillomavirus type 16 (viruses)", but also "Human papillomavirus type 161 (viruses)".

Is there a way recommended to extract a single genome reference matching either "Human papillomavirus type 16" or "333760" ? 

thanks!

**Comment by kblin** [comment]
I think the parameter you're looking for is `--taxids` or `-t`. That'd take your taxid of `333760` and download exactly that genome. It looks like the strain name of that particular strain is listed as "type 16" in the assembly summary file, so I guess
`ncbi-genome-download -t 333760 -F fasta,assembly-report -l complete viral` and `ncbi-genome-download -g "Human papillomavirus type 16" -F fasta,assembly-report -l complete -S "type 16" viral` both would work,

**Comment by kblin** [comment]
I don't have a paper or other DOI source for this at the moment, but feel free to cite it with a URL pointing to this GitHub repository.
