### ISSUE TITLE
DEBUG: Skipping over unexpected checksum line u''

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#18]
This line occurs a lot - should I be worried?

**Comment by kblin** [comment]
Nope, there's a reason this is a `DEBUG` thing. Things you should worry about should be logged at `ERROR` level. :-)

Kidding aside, I should probably just fix this. My md5sum parser doesn't like the trailing newline, so it writes this log message, but it's harmless noise.

**Comment by kblin** [comment]
Should be fixed by 60c8e2c
