### ISSUE TITLE
viral division has disappeared from NCBI 

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#19]
This just hangs:
```
ncbi-genome-download -r 2 -v -o viral -H -p 1 --debug -s genbank -F genbank viral
DEBUG: Downloading summary for 'genbank'/'viral' uri: 'https://ftp.ncbi.nih.gov/genomes'
INFO: Starting new HTTPS connection (1): ftp.ncbi.nih.gov
DEBUG: "GET /genomes/genbank/viral/assembly_summary.txt HTTP/1.1" 404 240
```

Going via web browser says:
```
Not Found
The requested URL /genomes/genbank/viral/assembly_summary.txt was not found on this server.
```

It seems 'viral` is not in the `genbank` folder?
https://ftp.ncbi.nih.gov/genomes/genbank/

The `refseq` folder has `viral` bit it is a dead symlink.
https://ftp.ncbi.nih.gov/genomes/refseq

Could be a victim of the NCBI FTP rearrangement?

**Comment by kblin** [comment]
Weird, according to https://ftp.ncbi.nih.gov/genomes/README.txt at least the RefSeq version should exist and not be a dead symlink.

**Comment by kblin** [comment]
https://ftp.ncbi.nih.gov/genomes/bacteria/ 404s for me right now, I think they just broke their HTTPS server. Just in time for their HTTPS tests today. The FTP server still works, but FTP downloads are a pain in Python.

**Comment by tseemann** [comment]
Poor NCBI has been making a mess of things lately with their reorganization :-(
But I can't imagine it would be easy to implement change!

**Comment by kblin** [comment]
No, especially as I'm not aware of any nice and easy to use library like `requests` that I use for HTTP(S) that works for FTP. So you're restricted to using the stdlib `ftp` library, which is... less fun to use.

**Comment by tseemann** [comment]
I get this error all the time:

```
ERROR: Download from NCBI failed: ConnectionError(MaxRetryError("HTTPSConnectionPool(host='ftp.ncbi.nlm.nih.gov', port=443): Max retries exceeded with url: /genomes/all/GCA_000828795.1_ASM82879v1/md5checksums.txt (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f81fe3cc8d0>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)
```

I've never had a full job finish properly yet (eg. a whole division).

**Comment by kblin** [comment]
I've never seen that here. Joys of being on the other side of the planet, I guess. But that's an OSI layer below, so I guess it's unrelated to the broken links.

**Comment by tseemann** [comment]
Really? We have so many issues with FTP and now HTTPS too... bummer :-(

**Comment by kblin** [comment]
"Network unreachable" sounds like a routing issue, no matter what protocol you use on top of that.

**Comment by kblin** [comment]
Huh, https://ftp.ncbi.nih.gov/genomes/refseq/viral/ works, but browsing there from https://ftp.ncbi.nih.gov/genomes/refseq/ doesn't. Fun times.

**Comment by kblin** [comment]
Seems to work now, I guess this was a hiccup on the NCBI side. Closing the issue, please reopen when it happens again.

**Comment by forestdussault** [comment]
Just came across your script today - nice work. Unfortunately it is hanging for me with the following command:

`ncbi-genome-download --assembly-level complete -F fasta --human-readable --verbose --debug bacteria`

The downloader will progress for a few minutes and then stop. It seems to stop while attempting to start a new HTTPS connection:

```
DEBUG: Skipping entry with assembly level 'Contig'
INFO: Downloading record 'GCF_000465235.1'
INFO: Starting new HTTPS connection (1): ftp.ncbi.nlm.nih.gov
```

**Comment by kblin** [comment]
Hi, thanks for the error report. I've opened up issue #50 to track this one, as it seems to be unrelated to this issue.
