### ISSUE TITLE
How can I reference ncbi-genome-download

### ISSUE THREAD

**Issue by padpadpadpad** [kblin/ncbi-genome-download#207]
Hi Kai Blin

Just wondering what the best way to reference your package is in academic publications. Had a quick search on Google Scholar and cannot find anything other than referencing the GitHub repo link.

**Comment by llxlr** [comment]
maybe we can use https://zenodo.org/

**Comment by peterjc** [comment]
Given Kai is using the GitHub Releases functionality, then the GitHub Zenodo integration shouldn't be any additional burden once setup.

**Comment by kblin** [comment]
The reason I haven't set this up is that from where I sit, I think the Zenodo setup is a bit backwards. I can only get a DOI assigned once I do the release. So the release can never have an accurate "how to cite this release" in it, because at the time I do the release I don't have a DOI for it yet.

**Comment by peterjc** [comment]
I agree, that aspect irks me too - so from my tool's GitHub page and documentation I just use the version-free DOI which currently Zenodo automatically redirect to the latest version, quoting my README:

> You can also cite the software specifically via Zenodo which offers version specific DOIs as well as https://doi.org/10.5281/zenodo.4529395 which is for the latest version.

Not ideal, but simple.

I have not yet setup a ``CITATION.cff`` file which is also worth considering:

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by kblin** [comment]
Hm, the Zenodo github plugin doesn't even allow me to pick up an existing release, and there's no way of knowing the version-free DOI before doing that release. So basically I need to have two releases that have no additional feature changes just to get a DOI going. :facepalm:

**Comment by peterjc** [comment]
Sounds plausible - it was a bit clunky to setup, but at the time I was still doing frequent point releases.

**Comment by kblin** [comment]
I figured I could get that down to only one release with creative abuse of tags for existing releases. The trick is to use a tag that's invalid for pypi so you're not creating extra releases there.

**Comment by kblin** [comment]
Hm, almost managed to get the right DOI into the README

**Comment by kblin** [comment]
Please use [DOI: 10.5281/zenodo.8192432](https://doi.org/10.5281/zenodo.8192432) to cite `ncbi-genome-download`
