### ISSUE TITLE
Support for filtering assemblies by sequencing platform?

### ISSUE THREAD

**Issue by JonathanAbrahams1337** [kblin/ncbi-genome-download#208]
I would like to filter assemblies by their sequencing platform before download, is that possible?

**Comment by kblin** [comment]
I don't think that's information that is available in the assembly summary table that `ncbi-genome-download` bases its download decisions on.

**Comment by JonathanAbrahams1337** [comment]
Yes, I think you are right, I was hoping the tool was cross referencing between different databases behind the scenes and had access to this type of data, but perhaps not.

No problem, thanks for your reply. This tool is very helpful.

**Comment by kblin** [comment]
No, we're just reading the assembly summary files. Maybe the [ncbi datasets tool](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/download-and-install/) does what you need?
