### ISSUE TITLE
FYI - NCBI doing "Genus species" folders now?

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#21]
Just FYI 

eg. all the latest `Leptospira_borgpetersenii` assemblies:

```
ftp://ftp.ncbi.nlm.nih.gov/genomes/genbank/bacteria/Leptospira_borgpetersenii/latest_assembly_versions/
```

**Comment by kblin** [comment]
Yeah, but that's exactly the same files, just a more human-readable way to find them again.

**Comment by kblin** [comment]
Closing this, as it's not really a question. :)

**Comment by tseemann** [comment]
You should add a `Label` called `statement` :)
