### ISSUE TITLE
can it download genomes of specific strains?

### ISSUE THREAD

**Issue by Liao-PRIC** [kblin/ncbi-genome-download#220]
I wonder if this program can be used to download genomic data of a specific strain or multiple strains? 
Because sometimes/usually there are multiple strains within a species, how to get the specific strain is very useful.
tried to add the strain name after the species name as below, but didn't work. Anyone can help me to solve this issue? Thank you very much!!!
 --genera "Streptomyces coelicolor X" bacteria #x is the strain name. but adding extra information like this causes error "No downloads matched your filter."

**Comment by kblin** [comment]
check out the `--strains` option, that should do what you want.
