### ISSUE TITLE
ncbi-genome-download shows error "Unsupported group"

### ISSUE THREAD

**Issue by Anju-h** [kblin/ncbi-genome-download#222]
I have been trying to download genomes using command for eg. "ncbi-genome-download --refseq-categories reference platyhelminthes", but I keep getting the error "Unsupported group: platyhelminthes". I have tried different combinations of options as well.
I was wondering is there a list or an option to see the supported format (or a name list) for a groups I wish to download genomes from ncbi.

**Comment by jrjhealey** [comment]
Unless the categorisation is part of the assembly summary file that ngd addresses, you cannot gather that information in this way. The file doesn't include information above I believe genus level.

You can use the script in the contrib/ folder gimme_taxa.py if you find out the TaxID at NCBI which corresponds to the Platyhelminthes group

**Comment by Anju-h** [comment]
I understand your point. But is there a way to find a list of the of the supported groups?
Also, Platyhelminthes/flatworms is a well described group, so it is hard to believe that there is not available information.

**Comment by kblin** [comment]
I can see how the term "group" here is confusing, but I am using the terminology NCBI used to describe things here. NCBI's "taxonomic groups" for FTP download purposes are "archaea, bacteria, fungi, invertebrate, metagenomes, plant, protozoa, vertebrate_mammalian, vertebrate_other, viral", corresponding to how NCBI organises the separate folders on their download servers.

As Joe mentioned, `ncbi-genome-download` is limited to the information the NCBI provides in the assembly summary files, which does not include a full taxonomy. The only things available are the "taxid", and the "species taxid". For any more complex taxonomy, check out the `gimme_taxa.py` script in the `contrib/` folder.

**Comment by Anju-h** [comment]
Thank you. It works
