### ISSUE TITLE
Recent issue downloading from GenBank but not RefSeq

### ISSUE THREAD

**Issue by raufs** [kblin/ncbi-genome-download#228]
**Describe the bug**

Stalls during download request from GenBank but not RefSeq. I have tried switching the `url` to the one with nlm - but to no luck. This is the second day of observing the issue.

**Affected version**

Version 0.3.3 installed via bioconda (pyh7cba7a3_0).

**To Reproduce**

This works well:

```bash
ncbi-genome-download -s refseq --genera Cutibacterium --flat-output -o test/ -u 'https://ftp.ncbi.nlm.nih.gov/genomes' bacteria -v
```

This doesn't work and seems to stall for upwards of an hour:

```bash
ncbi-genome-download -s genbank --genera Cutibacterium --flat-output -o test/ -u 'https://ftp.ncbi.nlm.nih.gov/genomes' bacteria -v
```

With the only message reported being:

```
INFO: Using cached summary.
```

**Additional context**

Thank you for developing this super useful program - not sure if there was just some recent change to the GenBank database or whether it is offline for a temporary time. Happy to provide any more info as needed. 

Also, as mentioned I tried with the two URLs for ncbi and also tried running it on two networks, in case my institute one was flagged recently for someone doing something NCBI didn't like. And turning off cache via the `-N` argument also does not seem to help.

Kind regards,
Rauf

**Comment by kblin** [comment]
Thanks for the report.

There's some issue with the NCBI servers at the moment, you'll see the same issue with trying to open https://ftp.ncbi.nlm.nih.gov/genomes/genbank/bacteria in the browser. Nothing much I can do from my side, I'm afraid.
