### ISSUE TITLE
Download genomes from assembly file

### ISSUE THREAD

**Issue by ChillarAnand** [kblin/ncbi-genome-download#229]
Feature Request:

There is new database FDA-ARGOS. For this we can download assembly file from https://www.ncbi.nlm.nih.gov/bioproject/231221

How to download all the genomes from the assembly file?

**Comment by kblin** [comment]
I don't think it's `ncbi-genome-download`'s job to understand those files.
Having said that, it should be trivial to write a little script to convert this file into one that `ncbi-genome-download` understands.

Something like this should work:

```bash
grep -e "^#" -v  /PRJNA231221_AssemblyDetails.txt | cut -d$'\t' -f1 > accs_to_download.txt
ncbi-genome-download --section genbank --assembly-accessions accs_to_download.txt --progress-bar bacteria
```
