### ISSUE TITLE
requests 2.4.3 is required

### ISSUE THREAD

**Issue by alartin** [kblin/ncbi-genome-download#23]
Hi,
Just try to install it under python 2.7.6, installation is Okay but it failed to launch and the error is:
    from requests.packages.urllib3.contrib import pyopenssl
ImportError: No module named packages.urllib3.contrib

This is due to the requests version is 2.2.1 but actually 2.4.3 is required.
It would be better to make requests >= 2.4.3 in the requirements.txt

**Comment by kblin** [comment]
Thanks for your error report. I've got a patch coming up that will change the dependency management around a bit. I'll make sure to require requests >= 2.4.3 for that.

**Comment by kblin** [comment]
Should be fixed by ﻿⁠⁠⁠⁠ab00b6c﻿⁠⁠⁠⁠. Please reopen this bug if this still doesn't work. I'll try to push this out in a 0.2.1 release soon, but am a bit short on time right now.

**Comment by kblin** [comment]
Just as a heads up, I finally got around to release a new ncbi-genome-download version that includes the correct requests dependency.
