### ISSUE TITLE
Can I also use this to download specific genus?

### ISSUE THREAD

**Issue by dutchscientist** [kblin/ncbi-genome-download#3]
As I am a small player with ditto diskspace, and usually only want the genomes from a specific genus, can this be done?

**Comment by kblin** [comment]
From the files provided by NCBI, this is not entirely trivial. I guess a string match on the `species_name` field would work. I'll add this to my todo list.

**Comment by dutchscientist** [comment]
OK, it's just that not everyone can afford to download the whole database :)

**Comment by kblin** [comment]
Yes, very good point. I didn't think about that use case before, but it seems pretty obvious now. Thanks a lot for the feedback.

**Comment by kblin** [comment]
Thanks again for your feedback. In version 0.1.6. that I just released, you can now limit the genus by using the `--genus` option.
Closed by 7232544
