### ISSUE TITLE
Make it usable as a regular python method

### ISSUE THREAD

**Issue by mbourqui** [kblin/ncbi-genome-download#30]
That is, allow to skip the command-line arguments parsing phase and use it in any python script as a regular method call.
Typical usage would be:

    import ncbi_genome_download as ngd
    ngd.download(section="refseq")

**Comment by mbourqui** [comment]
I forked your repo to work on that. Will submit a PR by next week.

**Comment by kblin** [comment]
That's almost possible already, you just need to provide an object that has all the required parameters that `argparse` puts into `args` that `download()` takes as parameter.

**Comment by mbourqui** [comment]
Yes, but that's a bit unpractical.

**Comment by kblin** [comment]
Sure, I'm open to better ways to handle this. Bonus points if it neither triggers pyflake's "too-many-arguments" checker nor repeats the default settings from the command line code in `__main__.py` :)

**Comment by kblin** [comment]
Arguably, not triggering the pyflakes checker might be hard, I've disabled it for `_download()` because I felt explicitly listing arguments was better than an opaque object, and this is mostly a coding style thing.

**Comment by mbourqui** [comment]
My idea is to use keywords arguments, so it will release the pyflake's complain. But your're right, it shadows the parameters.
I will also try to figure out a way to avoid duplicate default settings.

**Comment by mbourqui** [comment]
I will describe the parameters as comments. What commenting style were you using so far? I am used to the Numpydoc.

**Comment by kblin** [comment]
Just thinking, maybe a "default parameters" object or dictionary that you can use in both the kwargs loading and `add_argument` might be more elegant.
I have to admit that building command-lines for non-trivial tools in a way that also allow using them as a library but is also nice to read and doesn't repeat stuff is a problem I haven't figured out so far.

**Comment by kblin** [comment]
Hm, I don't think I've got a named comment style.

**Comment by mbourqui** [comment]
See #31 for my implementation proposal.

**Comment by kblin** [comment]
This is shipped for a while now.
