### ISSUE TITLE
Is it possible to use this script for higher taxon-levels than "Genus"?

### ISSUE THREAD

**Issue by jvollme** [kblin/ncbi-genome-download#32]
I frequently do genome comparisons between all currently known genomes of a given family, order, class or sometimes even phylum of bacteria. Downloading all currently available reference genomes can be laborious, so I was glad to find your script here.

However, currently I would like to download all available NCBI genomes of the phylum "Chloroflexi" (no matter which genus or species, as long as it's classified as "Chloroflexi". If possible I would like to include draft genomes which have not been assigned to a specific genus yet.).

I tried using your script with the "-t" option, giving the TaxID for the phylum "Chloroflexi" (which would be 200795). My exact program call was first: `ncbi-genome-download -F genbank -l all -t 200795 bacteria`.
then I tried with `ncbi-genome-download -F genbank -l all -T 200795 bacteria`

However nothing was downloaded.  I notice that you included a separate argument for "genus". Does that mean higher taxonomic levels than "genus" are not supported?
Would it be possible/feasible to support higher taxon-levels in the future?

**Comment by kblin** [comment]
This is not possible at the moment, as this is information that's not readily available from the NCBI FTP server. `ncbi-genome-download` looks at the `assembly_summary.txt` file, which only provides the organism name, taxid and species-level taxid (and other things that are not relevant from a taxonomy perspective).

The only way I see for providing the information required for a phylum-level download would be to talk to NCBI Entrez for the taxonomy information before running the download.

This is certainly possible, but drastically changes the focus from being a bulk-download tool to a much smarter and much more fragile Entrez client.

In a perfect world, I would recommend just talking to Entrez for both the taxonomy information and the sequences, but in my experience you can't rely on sequence data downloaded from Entrez to be complete and correct, and there's no way to verify. This was one of the main issues that drove me to write `ncbi-genome-download`.

Maybe a solution would be to make `ncbi-genome-download` accept a file with a list of taxids, and then download them in one go. Then you could generate the list of taxids to download by talking to Entrez, and then use `ncbi-genome-download` to grab the actual sequences. Would that help?

Until this feature is implemented, this less performant workaround might help.

```bash
for taxid in $(cat my_taxids.txt); do
    ncbi-genome-download -t $taxid
done
````
assuming that `my_taxids.txt` contains all the TaxIDs you want to grab, one per line.

**Comment by jvollme** [comment]
Thanks, 
I currently building a solution that would get me a complete list of taxids, but i'm not so familiar with Entrez and the output is rather frustrating.

So far I can get a list of uids of all "Genome" entries associated with the phylum "Chloroflexi" (double checked with the taxonomy browser that they are complete. It's 159 genomes so far).
Then i looped through the individual records through each of these uids in order to get more complete metainformation on each of those entries. Sadly there is no "TaxId" field there, so I thought I could make do with the "Organism_Name" fields and retrieve the respective  TaxId's in another step.

However, the Organism name is not complete in all cases! For example the uid "38157" SHOULD point to "Dehalogenimonas sp. WBC-2" (that would be TaxID "943347" which is recognized by your script), but instead it points simply to "Dehalogenimonas" (which would be the more higher level TaxID "670486" which is NOT recognized by your script).

So currently I am at a loss on how I can make sure to get such cases included in the automated genome download. 

Of course this is an issue with Entrez, and I'll ask elsewhere also. But if you may have any pointers for me on this topic, I'd be really grateful.

**Comment by kblin** [comment]
Hm, of course if you get a list of organism names, you can also use those with `nbci-genome-download`. If they are the same as in the assembly summary file.

If you have organism names with a space in them, the script is a bit more exiting, though,.
```bash
OLD_IFS=$IFS
IFS=$'\n'

for name in $(cat organism_names.txt); do
    ncbi-genome-download -g "$name"
done

IFS=$OLD_IFS
```

Hope this helps.

**Comment by jvollme** [comment]
Well the problem at the moment is that Entrez does not return the __full__ organism name in all cases. So I can't go that way either. It would be so simple if only I could search the "nucleotide" or "genbank" dbs using the "GenomeID"-uids returned from the "genome" database. But as far as I see that does not seem to be possible. If I use a "GenomeID" uid in a search of the "nucleotide" db, efetch assumes I am using an seqeunceID and returns the wrong sequence of a totally different organism (If it randomly happens to be identical to my genome-uid).
