### ISSUE TITLE
Bump to 0.2.4

### ISSUE THREAD

**Issue by mbourqui** [kblin/ncbi-genome-download#34]
Hi,

I would need the additional features from the latest pull requests. As it is part of a larger project, it would be much easier to use if available from PyPI. Are you planning to soon publish an update on PyPI?

**Comment by kblin** [comment]
I have a bunch of other deadlines at the moment that demand most of my work-time attention, but I should be able to push a release out early next week, I hope.

**Comment by mbourqui** [comment]
Ok, no stress, next week is great! Thank you :)
