### ISSUE TITLE
Support for proxies in requests

### ISSUE THREAD

**Issue by mbourqui** [kblin/ncbi-genome-download#35]
So far, the only way to set the proxies for the `requests` package is via `EXPORT`. It would be great to also support the proxies as parameter to `requests`, like here: http://docs.python-requests.org/en/latest/user/advanced/#proxies

I would see two options for that:
1. either to set the proxies via a sub-command, and then all the following calls to `ncbi_genome_download` will use those proxies. This would be reflected as a setter in `core.py`, such that it could also be set programmatically if using `download()`. Maybe more user-friendly, as usually proxy settings do not change bertween two calls.
1. set the proxies at each call of `ncbi_genome_download` via specific params. This would be reflected as keyword arguments to `download()`. Easier to implement.

If you do not mind, I will do a PR next week, as I need this functionnality anyway in my project. Let me know which solution (or an other one) you prefer!

**Comment by kblin** [comment]
Hey @mbourqui, I think I'd prefer solution 2, but to really tell I'd have to see the code.

**Comment by mbourqui** [comment]
Yes sure, it's better with code. I haven't started yet, but I think that by beginning of next week I will be able to submit a pull request with the second option.

**Comment by kblin** [comment]
As mentioned on the PR, please use `os.environ` to set your proxies.
