### ISSUE TITLE
Only 3 viral sequences downloaded?

### ISSUE THREAD

**Issue by 4ureliek** [kblin/ncbi-genome-download#41]
Hi,
I am trying to download all viral sequences from genbank in fasta format, equivalent of the search:
` ((viral)) AND "viruses"[porgn:__txid10239]`
This package looked very promising, so I tried the command below and few other variations. However, it only downloads 3 sequences. Am I missing something?
```
ncbi-genome-download -s genbank -F fasta -l all viral -v
INFO: Downloading record u'GCA_001857745.1'
INFO: Downloading record u'GCA_001857805.1'
INFO: Downloading record u'GCA_001857825.1'
```
Thank you!

**Comment by kblin** [comment]
No, I think it's the NCBI FTP server that is missing things. https://ftp.ncbi.nih.gov/genomes/genbank/viral/assembly_summary.txt only seems to contain three entries, and that's the ones `ncbi-genome-download` is grabbing.

**Comment by kblin** [comment]
You might want to grab the RefSeq set instead. That has many more records.

**Comment by 4ureliek** [comment]
Ha yes indeed... Thanks for checking! We already have refseq, and wanted all genbank (there are many more records in it), so I ended up just downloading from the browser. But for longer term I was hoping to find a command line to do the same thing!
