### ISSUE TITLE
Human readable path names and NCBI underscore escaping

### ISSUE THREAD

**Issue by peterjc** [kblin/ncbi-genome-download#45]
The NCBI don't just use standard percent escapes in the FTP site folder names, but instead replace certain characters with underscores.

e.g. using txid 613 problem cases include the ``#`` character:

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3#81/GCA_001564475.1_12082_3#81_genomic.fna.gz
-->
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/001/564/475/GCA_001564475.1_12082_3_81/GCA_001564475.1_12082_3_81_genomic.fna.gz

and brackets ``(`` and ``)``:

ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/468/075/GCA_000468075.1_Serratia_fanticola_AU-P3(3)/GCA_000468075.1_Serratia_fanticola_AU-P3(3)_genomic.fna.gz
-->
ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/468/075/GCA_000468075.1_Serratia_fanticola_AU-P3_3_/GCA_000468075.1_Serratia_fanticola_AU-P3_3__genomic.fna.gz

This is handled here in a related script which I have contributed to also fetches genomes by taxon from the NCBI FTP site:

https://github.com/widdowquinn/pyani/commit/585b8b6c80939ef5fbd26424e619254f0a87c363

This code replaces the following with an underscore: white space including `` ``, slash ``\``, comma ``,``, hash ``#``, brackets ``(`` and ``)``.

There is something similar in ``ncbi-genome-download`` where (if I have understood the context correctly) you make a local folder name which would ideally match the NCBI FTP naming convention:

https://github.com/kblin/ncbi-genome-download/blob/0.2.4/ncbi_genome_download/core.py#L375
https://github.com/kblin/ncbi-genome-download/blob/0.2.4/ncbi_genome_download/core.py#L574

This code replaces the following with an underscore: space `` ``, semi-colon ``;``, slash ``\``, back-slash ``/``.

It seems likely to me the two scripts have overlapping subsets of the full list of characters which the NCBI replaces with an underscore - but I'm not 100% sure of the use-case for your cleanup function.

**Comment by kblin** [comment]
I'm not sure I understand what you're getting at. The human-readable sorting is not trying to recreate the NCBI FTP naming convention. That's a relatively new feature on the NCBI side, the human-readable option is simply trying to put things into a folder structure that makes sense for humans.

Are you saying that GCA_001564475.1 fails to download due to some string escaping issue?

**Comment by peterjc** [comment]
OK, if you are not trying to recreate the NCBI FTP naming, that's fine. My misunderstanding.

**Comment by kblin** [comment]
I'm happy to have a conversation about the merits of recreating the NCBI FTP naming, but that'd be a new feature. :smile:
