### ISSUE TITLE
bioconda package - import error

### ISSUE THREAD

**Issue by aschuerch** [kblin/ncbi-genome-download#48]
I got an import error for enum in a brand-new conda environment. Is enum34 missing in the recipe? 
```
ImportError: No module named enum
```
(I now installed with pip which went just fine. Thank you for the effort to put it into bioconda, I appreciate it.)

Here's the output I got when installing the package:
```
$ conda create -n "genome_download" ncbi-genome-download
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /hpc/local/CentOS7/dla_mm/tools/miniconda2/envs/genome_download:

The following NEW packages will be INSTALLED:

    ncbi-genome-download: 0.2.5-py27_0  bioconda
    openssl:              1.0.2l-0              
    pip:                  9.0.1-py27_1          
    python:               2.7.13-0              
    readline:             6.2-2                 
    requests:             2.14.2-py27_0         
    setuptools:           27.2.0-py27_0         
    sqlite:               3.13.0-0              
    tk:                   8.5.18-0              
    wheel:                0.29.0-py27_0         
    zlib:                 1.2.11-0 

...
(genome_download)$ ncbi-genome-download bacteria
Traceback (most recent call last):
  File "/hpc/local/CentOS7/dla_mm/tools/miniconda2/envs/genome_download/bin/ncbi-genome-download", line 4, in <module>
    import ncbi_genome_download.__main__
  File "/hpc/local/CentOS7/dla_mm/tools/miniconda2/envs/genome_download/lib/python2.7/site-packages/ncbi_genome_download/__init__.py", line 2, in <module>
    from .core import (
  File "/hpc/local/CentOS7/dla_mm/tools/miniconda2/envs/genome_download/lib/python2.7/site-packages/ncbi_genome_download/core.py", line 8, in <module>
    from enum import Enum, unique
ImportError: No module named enum

```

**Comment by kblin** [comment]
Hm, I'll have to raise that with the bioconda folks. There's some advaced python installer magic going on to pick up the dependencies that only come in with python 2. I know this works fine when using `pip install ncbi-genome-download` on python 2, as I test with that. But I know bioconda does their own share of magic on top of the python installer, so maybe there's a conflict.

Thanks for reporting this, I'll investigate.

**Comment by kblin** [comment]
Oh, my mistake. I didn't realise bioconda completely ingnored the dependencies specified in the `setup.py` file used by `pip`, and that I need to also add the deps to the bioconda recipe. I'll fix this in a bit.

**Comment by kblin** [comment]
Patch to the bioconda recipe submitted, should be fixed in the bioconda repository soon.

**Comment by kblin** [comment]
Should be fixed in the current bioconda package. Thanks for reporting.

**Comment by aschuerch** [comment]
Thank you for the swift actions @kblin, I'll give it a go today!

**Comment by aschuerch** [comment]
Works without any problems now, thanks again!

**Comment by kblin** [comment]
Thanks again for reporting the issue.
