### ISSUE TITLE
Ability to download specific species

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#5]
I know you added `genus` but really need `species` too.

For example, *Staphylococcus aureus* has 1000s of assemblies and don't want the whole genus.

**Comment by kblin** [comment]
I assume a simple string match on the organism name would work for that as well?

**Comment by kblin** [comment]
While this is not documented, using "genus" should actually work for that use case as well. Just use `--genus "Staphylococcus aureus"` and you'll get what you want. I'm happy to take suggestions for a better name for that parameter.
Basically the check is
```python
if organism_name.startswith(opts.genus):
    download_stuff()
```
So if you wanted to download _Streptomyces_ and _Streptococcus_, `--genus Strepto` would work as well. :smile:

**Comment by tseemann** [comment]
Cool!  That works, wonderful.  

Maybe change your docs?

**Comment by kblin** [comment]
Thanks for the feedback, I've added a note to the README.
