### ISSUE TITLE
Lots of "ERROR: checksum mismatches" with Genbank download

### ISSUE THREAD

**Issue by dutchscientist** [kblin/ncbi-genome-download#53]
I suddenly get lots of "ERROR: checksum mismatches" with downloads from Genbank or RefSeq, due to a significant number of downloads not completing. But if I check the link given in the report, it is correct and the files can be downloaded from the FTP-server.

Have already tried to reduce the number of parallel downloads (first 4, then 2), but no effect. Any thoughts? I use the latest version, last week no problems.

**Comment by dutchscientist** [comment]
Have tried with wget, and same there. It looks like NCBI has introduced a limit of connections/downloads within a time period, blocking access temporarily. That would really be problematic.

This was from home, will try from a workcomputer by VPN.

**Comment by dutchscientist** [comment]
OK, today it is working fine. Have not tried multiple connections, but >2,000 Listeria genomes came through fine at the home PC. So may have been a temporary blip at NCBI?

**Comment by kblin** [comment]
I'd hope so. I know the Entrez API has a limit, I'm not aware of anything on the download server side.

**Comment by kblin** [comment]
Closing this, as it doesn't seem to be an issue with `ncbi-genome-download`
