### ISSUE TITLE
It doesn't seem to actually support comma-separated list.

### ISSUE THREAD

**Issue by kbshimmyo** [kblin/ncbi-genome-download#55]
(despite documentation saying so.  Tried quoting too.)

$ ncbi-genome-download -F fasta bacteria,viral
usage: ncbi-genome-download [-h] [-s {refseq,genbank}]
                            [-F {genbank,fasta,features,gff,protein-fasta,genpept,wgs,cds-fasta,rna-fasta,assembly-report,assembly-stats,all}]
                            [-l {all,complete,chromosome,scaffold,contig}]
                            [-g GENUS] [-T SPECIES_TAXID] [-t TAXID]
                            [-R {all,reference,representative}] [-o OUTPUT]
                            [-H] [-u URI] [-p N] [-r N] [-v] [-d] [-V]
                            {all,archaea,bacteria,fungi,invertebrate,plant,protozoa,unknown,vertebrate_mammalian,vertebrate_other,viral}
ncbi-genome-download: error: argument group: invalid choice: 'bacteria,viral' (choose from 'all', 'archaea', 'bacteria', 'fungi', 'invertebrate', 'plant', 'protozoa', 'unknown', 'vertebrate_mammalian', 'vertebrate_other', 'viral')

**Comment by kblin** [comment]
Hi,

this is a feature that was just added to the development version, it's not in a released version yet. So just to make sure, are you running the development version? How did you install `ncbi-genome-download`? From pypi? From Bioconda? From github?

**Comment by kbshimmyo** [comment]
Apparently through pip install.  It was a few days ago.  :)  Let me know if you need us to track down further.

**Comment by kblin** [comment]
Yeah, pip install gets you version 0.2.5, that can't do the comma-separated lists yet. That feature will land in 0.2.6 once I get around to releasing that.
In the meantime, you can just run `ncbi-genome-download` in a loop to do this. Like this:
```bash
for db in bacteria viral; do
   ncbi-genome-download -F fasta $db
done
```
This is slightly slower than the new version, but if you're really downloading all of bacterial and viral RefSeq like in that command, that extra time is negligible compared to the download time.

**Comment by kblin** [comment]
Sorry for the confusion there.

**Comment by kblin** [comment]
This is supported in the 0.2.6 release that I just pushed to github and pypi.
