### ISSUE TITLE
Parallel download for us with crappy FTP connections

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#6]
The FTP download is single threaded and is slow for us in Australia.

Would you consider an enhancement to have multiple download threads?

**Comment by kblin** [comment]
Sure. I guess that'll increase the memory requirements a bit as then you'd have to keep the parsed results of `assembly_summary.txt`in memory to partition it among threads, but I'm sure most people not running this on an embedded system can afford to spend the additional 20 MB RAM to speed up downloads :wink:

**Comment by kblin** [comment]
Closed by d037ccf
