### ISSUE TITLE
ncbi-genome-download: error: unrecognized arguments: --dry-run

### ISSUE THREAD

**Issue by phiweger** [kblin/ncbi-genome-download#64]
I downloaded the current version, but `--dry-run` does not seem to be an option when I call

```
ncbi-genome-download --dry-run bacteria
```

Thank you for looking into this,
Adrian

**Comment by kblin** [comment]
Yes, the README here on GitHub always reflects the latest development version. If you installed from pip, you have the latest released version that doesn't have the `--dry-run` feature yet.

**Comment by kblin** [comment]
This is now in release 0.2.7.
