### ISSUE TITLE
--taxids with input file is not working

### ISSUE THREAD

**Issue by nick-youngblut** [kblin/ncbi-genome-download#66]
I'm using `ncbi-genome-download      0.2.6                    py35_0    bioconda`

The following works:

```
ncbi-genome-download bacteria --format fasta --taxid 562
```

However, when I try to place the taxid in a file and provide that as input for `--taxid`:

```
ncbi-genome-download bacteria --format fasta --taxid my_taxids.txt
```

...I get `ERROR: No downloads matched your filter. Please check your options.` I've tried this with other taxids, and the same behavior occurs. 

It appears that this version of `ngd` doesn't accept a file that lists taxids, even if they work when provided as a comma-separated list.

**Comment by kblin** [comment]
Yes, that feature has not made it into a release yet. It will be available once I get around to cut the next release.

**Comment by kblin** [comment]
Duplicate of #65

**Comment by kblin** [comment]
Ah, no, misremembered.

**Comment by kblin** [comment]
This is in release 0.2.7 now.

**Comment by xie186** [comment]
Seems still not working with " --taxid my_taxids.txt".
