### ISSUE TITLE
Use batch rsync instead of FTP

### ISSUE THREAD

**Issue by tseemann** [kblin/ncbi-genome-download#7]
The NCBI FTP server supports `rsync://ftp.ncbi....` connections. 

Could you create a "batch file" and do this via a single rsync call?

So incremental updates are easy and fast?

**Comment by kblin** [comment]
After reading the rsync manpage again, I found the `--files-from` option, so I now have an idea how to do this. Might take a bit to implement, though.

**Comment by kblin** [comment]
After reading through the rsync docs again, I'm not convinced this is any different from what I'm doing already. `rsync` also only supports one transfer at the time, and I'm already downloading files only when the checksum of the local file differs from what is reported in the NCBI `md5checksums.txt` file. Am I missing anything `rsync` provides that the tool doesn't do via the HTTP downloads?

**Comment by tseemann** [comment]
`rsync` may be a bit faster, and would do block delta diffs for big files, but in this case we don't have that. So it's probably not much different, not worth the hassle.
