### ISSUE TITLE
Problem with downloading using an accession list

### ISSUE THREAD

**Issue by Anto007** [kblin/ncbi-genome-download#71]
I'm using the 0.2.7 version of your nice tool. However, the comma-separated accession list option does not seem to work. I'm getting the error message: "ERROR: No downloads matched your filter. Please check your options."

The command I used is this: ncbi-genome-download -F fasta -A Klebs_list.txt bacteria

I'm also attaching here the Klebs_list.txt in case you want to take a look
[Klebs_list.txt](https://github.com/kblin/ncbi-genome-download/files/2265677/Klebs_list.txt)

**Comment by kblin** [comment]
Hi,

If you want to load the accession list from a file, that file should contain one accession per line, like so:
```
GCF_000215745.1
GCF_000957705.1
...
```


If you want to put multiple accessions on the command line, then you need to use commas:
`ncbi-genome-download -A GCF_000215745.1,GCF_000957705.1 bacteria`

I'm sorry if that's not clear from the README. `ncbi-genome-download` is getting more and more complex and I'm still struggling on how to best create the documentation.

**Comment by MassiMolari** [comment]
I'm trying to download some assembly from metgagenomes using both taxid and GenBank assembly accession, here the commands:

ncbi-genome-download --dry-run --section genbank --taxid 652676 bacteria --metadata metadata.txt

and

ncbi-genome-download --dry-run --section genbank --assembly-accessions GCA_900118175.1,GCA_900117435.1,GCA_900118305.1,GCA_900118345.1,GCA_900118315.1 bacteria --metadata metadata.txt

But I'm getting the error message: "ERROR: No downloads matched your filter. Please check your options."

Could you please let me know what it is wrong? Thanks!

**Comment by kblin** [comment]
Hi, basically the reason is that you're trying to look for these accessions in the "bacteria" section of GenBank, but they're in the "metagenome" section. Having said that, that's a new section that `ncbi-genome-download` doesn't support yet, I'll make sure to add it right away.

**Comment by Anto007** [comment]
Hi Kai,

Since you mention that you're going to add support for downloading metagenome: I was wondering if there's any way that you can also add a flag that would facilitate automated download of all relevant metagenomes for a given biome, for e.g., if I wanted to download all 'insect gut metagenomes' on GenBank or all 'marine sediment metagenomes'? At the moment, there appears to be no tool available that can achieve this in a convenient manner and so it will be super-cool if ncbi-genome-download has this functionality too!

Thanks!

**Comment by MassiMolari** [comment]
Hi Kai,
thanks for explanation. Then I'm looking forward for the upgrade!!! :-)

**Comment by kblin** [comment]
Assuming your microbiomes are labeled the right way in the assembly summary, you will be able to. NCBI puts the description into the organism name, so `ncbi-acc-download --section genbank --genus "insect gut" metagenomes` will download all assemblies in genbank labeled "insect gut microbiome".

**Comment by Anto007** [comment]
Awesome, I too am looking forward to the new version of your ncbi-genome-download. Keep up the great work!

**Comment by Anto007** [comment]
Wait a minute, I'm a bit confused now: surely you mean the upcoming version of ncbi-genome-download when you say "**ncbi-acc-download** --section genbank --genus "insect gut" metagenomes"? Correct?

**Comment by kblin** [comment]
The current one, as of now. :wink:

**Comment by kblin** [comment]
and yes, `ncbi-genome-download`, not `ncbi-acc-download`. Sorry.

**Comment by MassiMolari** [comment]
I saw the changes, thats great! Thanks!
I tried to re-install it via conda, but still I have the "old" version without the upgrade...
How can I solve this?

**Comment by kblin** [comment]
bioconda has a bot that updates packages, but apparently it was having issues today and didn't pick up the release. might take another day or two to get a manual package update in

**Comment by MassiMolari** [comment]
Hi Kai,
I see, thank you for explanation. Then I will try in next days.
