### ISSUE TITLE
Download a sequence from RefSeq by accession

### ISSUE THREAD

**Issue by sjackman** [kblin/ncbi-genome-download#76]
I'd like to download the sequence for `NC_005278.1` from RefSeq.
https://www.ncbi.nlm.nih.gov/nuccore/NC_005278.1?report=fasta

I tried…
```
ncbi-genome-download all -A NC_005278.1
❯❯❯ ncbi-genome-download all -A NC_005278.1
ERROR: No downloads matched your filter. Please check your options.
❯❯❯ ncbi-genome-download --version
0.2.7
```

What I'd really like more than anything is an URL for this sequence that I can download using curl.

**Comment by kblin** [comment]
Hi Shaun,

`ncbi-genome-download` only knows about accession ids that are in the assembly summary files the NCBI provides on their FTP server, and that contains the assembly accession ids, not the sequence accession ids.

For your use case, I'd recommend another script I've written that can download sequences by sequence accession id via their Entrez API: https://github.com/kblin/ncbi-acc-download

It doesn't produce a URL but does the download directly, but I'm happy to add a flag to just print the URL.

Hope this helps.

**Comment by sjackman** [comment]
Excellent! Thanks, Kai! It worked like a charm
```sh
ncbi-acc-download -Ffasta -v NC_005278.1
```
Oh except for one small thing. There's an extra blank line at the end of the FASTA file, which could break some FASTA parsers.
```
❯❯❯ cat -n NC_005278.1.fa | tail -n2
   236	TTTTACCCCATAA
   237	
```

> It doesn't produce a URL but does the download directly, but I'm happy to add a flag to just print the URL.

A flag to print just the URL would be great. Perhaps `--url`
Additionally perhaps `-v` could print `Downloading ${URL}...`

**Comment by kblin** [comment]
I'm just dumping the Entrez output to a file, I'm not futzing with the newlines. That's NCBI sending `\n\n` as the end of the stream.

**Comment by kblin** [comment]
I've just released ncbi-acc-download 0.1.2 that includes the `--url` parameter, the `-v` improvement and a fix for the Biopython dependency you reported.

**Comment by sjackman** [comment]
Thanks, Kai! That's fantastic.

**Comment by sjackman** [comment]
The Entrez-Direct web API does return two line feeds, as you say.
```
❯❯❯ curl -s 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?retmode=text&rettype=fasta&db=nucleotide&id=NC_005278.1' | xxd | tail -n2
0004120: 4154 4143 4141 4154 4141 5454 0a54 5454  ATACAAATAATT.TTT
0004130: 5441 4343 4343 4154 4141 0a0a            TACCCCATAA..
```

Their command line interface however returns only a single line feed.
```
❯❯❯ efetch -db nuccore -id NC_005278.1 -format fasta | xxd | tail -n2
0004120: 4154 4143 4141 4154 4141 5454 0a54 5454  ATACAAATAATT.TTT
0004130: 5441 4343 4343 4154 4141 0a              TACCCCATAA.
```

So it looks like a bug in their web API.

A workaround is two pipe the output into `seqtk seq`, which I usually do anyway to strip the line feeds from the middle of the sequence.

```
❯❯❯ curl -s 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?retmode=text&rettype=fasta&db=nucleotide&id=NC_005278.1' | seqtk seq | xxd | tail -n2
0004040: 4154 5454 5454 5441 4343 4343 4154 4141  ATTTTTTACCCCATAA
0004050: 0a                                       .
```

**Comment by kblin** [comment]
Not sure this really is a bug in their web UI, to be fair. It does allow them to stream multiple records that are separated by an empty line.
As the FASTA format as used in the original FASTA tool ignored these line breaks, I'd consider this to be a valid FASTA file.

In any case, your workaround certainly tackles this just fine.
