### ISSUE TITLE
Conda install does not work.

### ISSUE THREAD

**Issue by vinisalazar** [kblin/ncbi-genome-download#80]
Hi,

Your conda packaging does not seem to be working... It gets stuck in the 'resolving package specifications' step. I doubt that the cause for that is my conda setup or anything else, because I installed some other packages earlier today with no problems whatsoever.

This is just a heads-up, I could install perfectly with `pip`.

Also, THANKS A LOT FOR THIS PACKAGE. It saved me.

Regards,

V

**Comment by jrjhealey** [comment]
Have you got any more details? `conda install ncbi-genome-download` worked for me just fine a few moments ago. Have you re-attempted it since?

**Comment by vinisalazar** [comment]
Hi,

I have just re-attempted it. I get stuck on the 'solving environment step'. This does not happen with any other packages, but regardless I'm guessing it is a problem on my end.

**Comment by druvus** [comment]
Could you please try `conda create -n ngd-test ncbi-genome-download`? I suspect you have some other tool installed with pinned dependency in you root environment.

**Comment by vinisalazar** [comment]
Hi @druvus, that worked indeed. I don't know why I didn't try it before. Thanks

**Comment by danudwary** [comment]
(Created a new issue #81 )
