### ISSUE TITLE
download for different groups

### ISSUE THREAD

**Issue by semihorhanbio** [kblin/ncbi-genome-download#91]
Is that possible to increase groups names? Script is just accepting the virus and bacteria as a group. But I have various group of organism such as Eukaryota.

**Comment by kblin** [comment]
Hi there!
If you run `ncbi-genome-download --help`, you'll see all the supported groups. We use "bacteria" and "viral" as an example in the docs, but the available groups should cover all that is available from the NCBI.
This possibly could be made a bit clearer in the documentation, sorry about that.

**Comment by kblin** [comment]
0610e43 hopefully improves the wording.

**Comment by kblin** [comment]
This is addressed in the 0.2.11 release.
