### ISSUE TITLE
Is it possible to download all genomes belonging to species of a viral genus ?

### ISSUE THREAD

**Issue by Niicii** [kblin/ncbi-genome-download#92]
I would like to download all genome sequences available for species included in a viral genus e.g. Fabavirus (TaxID 12269, contains 9 species). Out of the 9 species in this example, 7 have an RefSeq genome available while 2 only have a genome included in the INSDC database.  

If I supply the TaxID or name of the genus with `-t` or `-g`, respectively I would assume to get 7 genomes downloaded but rather get the following messages: 
```
(base) lwen@NAK-Test-02:~$ ncbi-genome-download -t 12269 -F fasta viral
ERROR: No downloads matched your filter. Please check your options.
(base) lwen@NAK-Test-02:~$ ncbi-genome-download -g Fabavirus -F fasta viral
ERROR: No downloads matched your filter. Please check your options.
```
I tried to specify the NCBI section using `-s genbank` but the result was the same error message. 

When individually specifying the species TaxIDs all genomes are downloadable. But that would require to search out the TaxIDs for each species contained in a genus and be unpractical for bigger viral genera...

**Comment by kblin** [comment]
This is something that `ncbi-genome-download` can't do standalone with the information available from NCBI's FTP server.

Fortunately, that's exactly what the use case of the `gimme_taxa.py` script in `contrib/` is for, thanks to @jrjhealey for contributing that. The README file has an example on how to use that.

**Comment by jrjhealey** [comment]
As Kai said! Please give the script a try and let me/us know of any ways to improve it!

Just a small word of warning, we’ve noticed recently that some entries can fail to be retrieved with it (it appears to be some quirks of the `ete3` package which does all the heavy lifting behind the scenes that I’ve not figured out).

It will probably be fine for your needs, but you may need to do some sanity checking on the number of genomes you retrieve.

**Comment by Niicii** [comment]
Thanks for the suggestions, I will give it a try soon.
