### ISSUE TITLE
i want to translate README.md

### ISSUE THREAD

**Issue by jamesyangget** [kblin/ncbi-genome-download#93]
Could I translate the README.md into Chinese?  I'm excited to use this package

**Comment by kblin** [comment]
Hi there,

My main problem with translations is that I can't keep them up to date when I change something, so they'll slowly drift away from the English language file. This isn't too bad for when it's just missing some newer features, but gets bad if I ever need to change the behaviour of a feature.

I see how having a Chinese translation will make life easier for Chinese native speakers, but given the maintenance issue I'm really not sure how to handle this.

**Comment by kblin** [comment]
After thinking about this a bit more, I think I'd be happy to accept this if you can add a disclaimer at the start that the translation might be outdated and people should always check with the English file to get the most up-to-date version.

**Comment by jamesyangget** [comment]
you are right, i add this in start:
![Snipaste_2019-09-04_00-07-10](https://user-images.githubusercontent.com/33483752/64190240-79838200-cea8-11e9-8328-5a0befc606da.jpg)
can it?

**Comment by jamesyangget** [comment]
ok
